# Generated by Django 3.1.5 on 2021-12-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211216_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_name',
            field=models.CharField(db_column='book_name', default='', max_length=64),
        ),
    ]
